# Generated by Django 3.2.6 on 2021-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('bvid', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('cover', models.CharField(max_length=80)),
                ('num_view', models.IntegerField()),
                ('num_like', models.IntegerField()),
                ('num_coin', models.IntegerField()),
                ('num_favorite', models.IntegerField()),
                ('up_id', models.IntegerField()),
                ('up_name', models.CharField(max_length=40)),
                ('up_face', models.CharField(max_length=80)),
                ('upload_time', models.CharField(max_length=20)),
                ('reply', models.JSONField()),
            ],
        ),
    ]
