# Generated by Django 3.2.6 on 2021-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id']},
        ),
    ]
