# Generated by Django 3.2.6 on 2021-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_list', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='aid',
            field=models.IntegerField(unique=True),
        ),
    ]
