# Generated by Django 3.2.6 on 2021-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_list', '0003_alter_video_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='up_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
